### PR TITLE
Syntax: Added the description that global variables use the $ prefix

### PR DESCRIPTION
**Pull request by schittli**
Hello François 

I have just added very small information about global variables. I hope it is useful...

Thanks a lot, kind regards,
Thomas

### CODE REVIEW

**Comment by francois** [comment]
Hi! Thanks for your changes. I thought that *using * global variables was described correctly starting at line 203 and onwards? What can I do to make things clearer?

**Review by IotaBread — APPROVED** [review]

**Comment by schittli** [comment]
Hello @francois 

I think that you have not explicitly mentioned that all global variables have a `$` as a prefix.

If I'm right, then it would be very useful to note it explicitly. Otherwise, one must guess the meaning of `$`

**Comment by francois** [comment]
@schittli thanks for your time. I changed the text according to the need you identified.

**Comment by schittli** [comment]
Thanks a lot for your completion of the documentation.

**Pull request closed without merging**
