### PR TITLE
Added support for running Mindcode locally

### LINKED ISSUE #27: Compiling the mindcode project does not work since the release `"Prepared separate web application using Spring Web"`
Good morning @francois 

Thanks a lot for all your work!, 
I have tried to compile mindcode and used your _Native installation_ guide. Until to the commit from Apr 12, 2021 `Permit "indirect" sensor references` compiling works perfectly:

```
git checkout 03ecee928ce36ae33303e2b37f428c2f63634adb
mvn clean compile exec:java
… everything Ok
```
But if I move to the next release, [Github Commit: `Prepared separate web application using Spring Web`](https://github.com/francois/mindcode/commit/ab1ad052502e8f24a404cc064ca9840316b38534) I get a compiler error:
```
git checkout ab1ad052502e8f24a404cc064ca9840316b38534
mvn clean compile exec:java

[INFO] Reactor Summary:                                                                                                                                    
[INFO]                                                                                                                                                     
[INFO] mindcode-compiler 1.0.0 ............................ FAILURE [  3.806 s]                                                                            
[INFO] webapp 0.0.1-SNAPSHOT .............................. SKIPPED                                                                                        
[INFO] Mindcode 1.0.0-SNAPSHOT ............................ SKIPPED                                                                                        
[INFO] ------------------------------------------------------------------------                                                                            
[INFO] BUILD FAILURE                                                                                                                                       
[INFO] ------------------------------------------------------------------------                                                                            
[INFO] Total time:  4.383 s                                                                                                                                
[INFO] Finished at: 2021-04-20T10:43:38+02:00                                                                                                              
[INFO] ------------------------------------------------------------------------                                                                            
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project mindcode-compiler: The parameters 'mainClass' for go
al org.codehaus.mojo:exec-maven-plugin:3.0.0:java are missing or invalid -> [Help 1]
…
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
```

Unfortunately, I don't know Maven at all, so it's a bit tricky to find the cause. About Java, I know the version is always important - it's fine, I guess:

```
java.exe -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
C:\GitWork\Clones\GitHub\Game - Mindustry - mindcode\src [(ab1ad05...)]

mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Portable\Java-Maven\apache-maven-3.6.3\bin\..
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: C:\Portable\Java-JDK\jdk-11
Default locale: de_CH, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

I can not attach a html-file with the output of `mvn clean compile exec:java -e` and `mvn clean compile exec:java -e -X`, therefore I have added a pdf, so that the colors are preserved - this is much easier to read.

[mvn clean compile exec_java -e -X.html.pdf](https://github.com/francois/mindcode/files/6342135/mvn.clean.compile.exec_java.-e.-X.html.pdf)
[mvn clean compile exec_java -e.html.pdf](https://github.com/francois/mindcode/files/6342136/mvn.clean.compile.exec_java.-e.html.pdf)

I really hope this is just a minor config issue. Please let me know if I can send you more information.

Thanks a lot, kind regards,
Thomas

### PR DESCRIPTION
**Pull request by francois**
Resolves #27

### CODE REVIEW

**Comment by francois** [comment]
@schittli, could you kindly checkout this PR and tell me if the Windows script works? Look at `bin\run-local.cmd`.

It's been a *very* long time since I wrote Windows command files!

Thanks!

**Comment by schittli** [comment]
Thanks a lot for writing the windows batch file!, @francois , I have a few suggestions.

### Unit Tests, ProcessBuilder, `diff`and Windows

Because we now have `run-local.cmd`, therefore I guess that the tests should also run.
Because windows does not know `diff`, I have googled for Java unit tests using ProcessBuilder() with different operating systems. Some developers use this concept to to distinguish between the OS in the code:
File: `webapp\src\test\java\info\teksol\mindcode\webapp\SamplesTest.java`
```
    private void compile(String program, File source) throws IOException {
        final boolean isWindows = System.getProperty("os.name").toLowerCase().contains("win");
        …
        final Process diff = new ProcessBuilder()
                .command(isWindows ? "fc.exe" : "diff", "-u", unoptimizedTarget.getAbsolutePath(), optimizedTarget.getAbsolutePath())
                .redirectOutput(diffTarget)
                .start();
    }
```

At least, on Windows, this code works.

**Comment by francois** [comment]
Oh yeah, I had forgotten about that part. I’ll copy your code and make it work here. Then you can try it on Windows.

Thanks!
François

**Comment by schittli** [comment]
### Feedback to `bin\run-local.cmd` 

Good evening @francois 

For not having written a Windows Command File for a long time, your file `bin\run-local.cmd` looks very good :-)

Nevertheless, I have two hints:

#### 1) PowerShell would be the better solution

1. This Sub-Command is a PowerShell Command and does not work in cmd: `"$((Get-ChildItem .\webapp\ *.jar -Recurse | select -ExpandProperty FullName) -join ';')"`
2. Because by now Linux, even MacOS and every Windows has PowerShell for a long time, I would use PowerShell for this script and not Windows cmd anymore. I will make a suggestion.

#### 2) Nevertheless, as a cmd refresher:
1. Calling another cmd must use `call …`, so this is better: `call mvnw.cmd install`
2. `Echo` does not need `"`. If they are used, cmd will print them, which looks ugly

So that would be the better version, but the java call doesn't work because it just consists of a PowerShell command:

```
@echo off

rem In order to prevent the important information from being obscured,
rem compile Mindcode, THEN give important information to get it working.
rem This way, if Mindcode can't start, the important information will be
rem available right above the failure.
call mvnw.cmd install

echo *****
echo *****
echo ***** To run Mindcode locally, you need to have a PostgreSQL database accessible.
echo ***** You have a few choices:
echo *****
echo *****     - Install PostgreSQL for Windows: https://www.postgresql.org/download/windows/
echo *****
echo *****     - Use Docker to run PostgreSQL:
echo *****
echo *****           Download Docker from https://www.docker.com/get-started
echo *****           Once done, start a PostgreSQL instance:
echo *****               docker run -p 5432:5432 --name mindcode -v mindcode -e POSTGRES_HOST_AUTH_METHOD=trust postgres:latest
echo *****
echo ***** If your PostgreSQL instance is not available at postgres://127.0.0.1:5432/mindcode_development, edit
echo ***** both Spring configuration files and set the correct values:
echo *****    webapp\src\main\resources\application.properties
echo *****    webapp\src\test\resources\application.properties
echo *****

java -classpath "$((Get-ChildItem .\webapp\ *.jar -Recurse | select -ExpandProperty FullName) -join ';')" info.teksol.mindcode.webapp.WebappApplication
```

**Comment by schittli** [comment]
### Proposal to replace `bin\run-local.cmd` by PowerShell

`bin\run-local.cmd` has one advantage: it's small, but the Java-Call does not work (as already mentioned)

Therefore, I propose to change to PowerShell. I have written an example that is doing the following steps.
I can send you the PowerShell file as a change request, but I only do this two or three times a year, therefore I'm not a pro doing this. If you want, I can also reduce the script to the minimum, my solution currently performs these steps:

1. In webapp\src, it searches for the `application.properties` files
2. It reads the `spring.datasource.url` setting
3. … and it tests if the PostgreSQL Port is open
4. If the Port is not accessible, then the scripts stops and displays the Message `To run Mindcode locally, you need to have a PostgreSQL database accessible. …`
5. If the PostgreSQL Port is accessible, it starts `.\mvnw.cmd` install
6. If `.\mvnw.cmd` has an error, the Script stops
7. Then, java will be started

The Scrip-Start with the connection-tests looks like this:
image

In case you want to see it in action, I've captured the whole webapp-startup in a gif: https://imgur.com/jrh84HR

This would be the script which I would send you in a change request:
[run-local.ps1.txt](https://github.com/francois/mindcode/files/6361129/run-local.ps1.txt)

**Comment by francois** [comment]
I'm 100% open to using PowerShell. Last time I used Windows for development was 13 years ago! If you can share the PowerShell script, please do so. That will be very helpful, as I don't have a Windows environment to test in.

**Comment by schittli** [comment]
> I'm 100% open to using PowerShell. Last time I used Windows for development was 13 years ago! If you can share the PowerShell script, please do so. That will be very helpful, as I don't have a Windows environment to test in.

Good evening @francois 

I don't ask because I'm impatient 🙂, but it could be that we're waiting for each other, which would be unfortunate... hence the question:

Did you see that I created the pull request with the PowerShell script? [pull 29](https://github.com/francois/mindcode/pull/29)
I've been struggling with Git / Github and it was the best I could do on the third try.

I will do my best to correct any change requests asap and once the pull request is integrated, I will test it again.

**Comment by francois** [comment]
Hi, sorry about the delay. I received my COVID-19 shot this weekend and wasn't up to working on open-source. I should get around to this PR sometime this week. Thanks again for your effort!

**Comment by schittli** [comment]
Oh... this is actually good news :-) - so, we're jumped from 1'040'000'000 Vaccinated people to 1'040'000'001

The progress is better than it looks :-)

**Comment by francois** [comment]
@schittli, I have updated this PR with your latest changes. If you had time to retest another time, I'd really appreciate! Thanks a bunch :)

**Pull request merged**
