### PR TITLE
Add getBlock to MINDUSTRY-TIPS-N-TRICKS.markdown

### PR DESCRIPTION
**Pull request by limonovthesecond2**
There are currently no code examples for the "getBlock" command. Many people, like me, at first tried to get the result of the command using "building = getBlock(x, y)", not seeing the result, they thought that Mindcode could not use such a command. Therefore, I consider it necessary to have an example of using this command.

### CODE REVIEW

**Comment by cardillan** [comment]
That's a great idea! I was a bit worried Mindcode doesn't come with some helpful tutorial and the learning curve is too steep. This is definitely a welcome improvement in this regard.

I'd propose a few small changes to your version:

1. To rename the section  "Detecting destroyed buildings" to "Obtaining buildings" or "Locating buildings" or something in this vein, as `getBlock` allows you to do a lot more than just detect whether a building is dead.
2. I think it would be better to create a separate level 2 section "Using buildings" located after the "Using units" - since units need to be mastered first for `getBlock` and `ulocate` - and moving both your new subsection and "Locating the core" into it. It might be expanded with an example of `getlink` at some later time.
3. Maybe add a link to http://mindcode.herokuapp.com/?s=upgrade-conveyors for illustration somewhere, since this example also uses the `getBlock` function.

If you can't make these changes at this moment, let me know, I'll merge this PR as it is. It's already very useful.

If there are other issues you've stumbled upon when learning Mindcode, I'd love to hear about them too. (One thing I'm aware of is that syntax errors are sometimes hard to figure out - do you experience it too? I'm pondering updating the syntax and hearing about your experience could help me a lot.)

**Comment by cardillan** [comment]
Just two more points I've forgotten to add:

- It's a very nice example!
- Do you know about the [printf](https://github.com/cardillan/mindcode/blob/main/doc/syntax/SYNTAX-4-FUNCTIONS.markdown#printf) function? You could use `print("Enemy turret at $outx, $outy still exists\n")`.

**Comment by limonovthesecond2** [comment]
> Just two more points I've forgotten to add:
> 
>     * It's a very nice example!
> 
>     * Do you know about the [printf](https://github.com/cardillan/mindcode/blob/main/doc/syntax/SYNTAX-4-FUNCTIONS.markdown#printf) function? You could use `print("Enemy turret at $outx, $outy still exists\n")`.

- I wanted to add a small example, so it's quite useless, but if you add external memory and add an enemy target attack in addition to approaching, it would be pretty interesting code for an auto attack. All units will attack only one target at the same time with automatic change of targets when destroyed.

- Somehow just forgot about printf. Thank you for reminding!

**Comment by limonovthesecond2** [comment]
Syntax errors are indeed sometimes hard to understand(

- It would be great to point to a specific line of code when an error occurs. For example, today i changed `print` to `printf` without changing the options to `$`. The compiler said: "Can’t compile source code". I only found the error when i commented out all the printf.
- In a nested if-else, when you lost the end in the nested expression, an error appears in the first. Example:
```
target1 = switch1.enabled
if target1 == 1
    target2 = switch2.enabled
    if target2 == 1
        print("true")
    en
end
```
Error appears on line 2, not 4
- The compiler counts lines from 1 when Mindustry Logic counts from 0. It may also be better or not to count in such way too
- Maybe it would be better to warn when a null function is assigned to a variable. For example: `building = getBlock(0, 0, type, building)`.
- The documentation does not have a MindCode - Mindustry Logic equivalent, as in [#74](https://github.com/cardillan/mindcode/issues/74#issuecomment-1439207407)
- When you write functions or keywords that don't exist, the compiler simply ignores them. It may or may not be better to warn when the user write `iff`, `getBlock(block)` etc

**Comment by limonovthesecond2** [comment]
Make all changes as requested. Please check if there is anything else that needs to be done?

**Comment by cardillan** [comment]
Thanks for the feedback! I intend to improve error handling someday, and this will help a lot. 

> * The compiler counts lines from 1 when Mindustry Logic counts from 0. It may also be better or not to count in such way too

I get your point, but it looks like to me that most code editors number the lines from 1 - I prefer the 1-based numbering for this reason.

> * Maybe it would be better to warn when a null function is assigned to a variable. For example: `building = getBlock(0, 0, type, building)`.

Oh, I see. I didn't realize it. Yes, such a warning could be generated.

You might like using the 7A language version better: https://github.com/cardillan/mindcode/blob/main/doc/syntax/SYNTAX-4-FUNCTIONS.markdown#mindustry-logic-functions. In the 7A version, getBlock returns a variable.

> * The documentation does not have a MindCode - Mindustry Logic equivalent, as in [#74](https://github.com/cardillan/mindcode/issues/74#issuecomment-1439207407)

Do you mean these files?

- https://github.com/cardillan/mindcode/blob/main/doc/syntax/FUNCTIONS_V6.markdown
- https://github.com/cardillan/mindcode/blob/main/doc/syntax/FUNCTIONS_V7.markdown
- https://github.com/cardillan/mindcode/blob/main/doc/syntax/FUNCTIONS_V7A.markdown

They aren't part of the documentation "chain",  but they are linked from [here](https://github.com/cardillan/mindcode/blob/main/doc/syntax/SYNTAX-4-FUNCTIONS.markdown#mindustry-logic-functions). Do you think putting them into the chain would make them more visible? Or perhaps put them also [here](https://github.com/cardillan/mindcode/blob/main/doc/syntax/SYNTAX.markdown)?

> * When you write functions or keywords that don't exist, the compiler simply ignores them. It may or may not be better to warn when the user write `iff`, `getBlock(block)` etc

I get an error on `getBlock(block)` - the unspecific one, "Error compiling source code." But `getBlock(x, y)` compiles - this is because other parameters are optional (see https://github.com/cardillan/mindcode/blob/main/doc/syntax/FUNCTIONS_V7.markdown#instruction-ucontrol). Using just `getBlock(x, y)` doesn't make sense, because it doesn't use any output. Perhaps that could be disallowed or warned about.

**Comment by limonovthesecond2** [comment]
> Do you mean these files?

Yes, don't know there are so many information ahead of the documentation "chain". Putting links to them into "SYNTAX.markdown" and somewhere else in the "chain" would make them more visible.

>  But getBlock(x, y) compiles - this is because other parameters are optional

My fault. I haven't tested it rigorously enough.

**Comment by cardillan** [comment]
@limonovthesecond2 FYI, I've updated the documentation to make function reference more prominent, as you suggested.

**Pull request merged**
