### PR TITLE
add windows native installation help

### PR DESCRIPTION
**Pull request by k88936**
to record my tearful experience and to blame my struggling computer

### CODE REVIEW

**Comment by cardillan** [comment]
I'm sorry to hear you had trouble getting Mindcode to run locally. Could you send me the logs from your Docker run? I'm not very well versed in it, or in bash, but perhaps I'll be able to figure something out. I'd still want to support Docker as the primary solution, and when I tried it on the latest commit, it worked in my environment. There might be some specific setting I've done and forgotten about.

It's a good idea to expand the Windows specific documentation, including the bits about running the app from Idea. There are certainly some steps missing from the documentation, such as setting the `JAVA_HOME` environment variable. I'll get to this in a few days.

I'll probably add a batch file to compile the project from command line (it will just run `mvnw.cmd install`). There's also the `bin/webapp.bat` file, which should run the webapp outside of IDE. Both of these require the `JAVA_HOME` variable I've mentioned earlier - in my case, it is 

```
JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-17.0.6.10-hotspot
```

I'll get to this in a few days - I'm a bit busy at the moment.

**Comment by k88936** [comment]
docker-compose up --build
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 88, in main
  File "compose\cli\main.py", line 140, in perform_command
  File "compose\cli\main.py", line 900, in up
  File "compose\project.py", line 385, in up
  File "compose\project.py", line 590, in warn_for_swarm_mode
  File "site-packages\docker\api\daemon.py", line 73, in info
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\api\client.py", line 179, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1042, in request
  File "httplib.py", line 1082, in _send_request
  File "httplib.py", line 1038, in endheaders
  File "httplib.py", line 882, in _send_output
  File "httplib.py", line 844, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', '\xcf\xb5\xcd\xb3\xd5\xd2\xb2\xbb\xb5\xbd\xd6\xb8\xb6\xa8\xb5\xc4\xce\x
c4\xbc\xfe\xa1\xa3')
Failed to execute script docker-compose


mabe something n docker itself .i have to say latest docker doesnot support my win7 so i dont know whether it will occur there

**Comment by k88936** [comment]
$ bin/run-local -e
[WARNING]
[WARNING] Some problems were encountered while building the effective settings
[WARNING] Unrecognised tag: 'profile' (position: START_TAG seen <settings>\r\n<profile>... @2:10)  @ C:\Users\k88936\.m2\settings.xml, line 2, column 10
[WARNING]
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Mindcode                                                           [pom]
[INFO] mindcode-mindcode                                                  [jar]
[INFO] mindcode-schemacode                                                [jar]
[INFO] mindcode-webapp                                                    [jar]
[INFO] mindcode-compiler                                                  [jar]
[INFO]
[INFO] -------------------< info.teksol.mindcode:mindcode >--------------------
[INFO] Building Mindcode 1.0.0-SNAPSHOT                                   [1/5]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.5.0:copy-dependencies (copy-dependencies) @ mindcode ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ mindcode ---
[INFO] Installing E:\WORKSPACE\mindcode\pom.xml to C:\Users\k88936\.m2\repository\info\teksol\mindcode\mindcode\1.0.0-SNAPSHOT\mindcode-1.0.0-SNAPSHOT.pom
[INFO]
[INFO] ---------------< info.teksol.mindcode:mindcode-mindcode >---------------
[INFO] Building mindcode-mindcode 1.1.0-SNAPSHOT                          [2/5]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.9:prepare-agent (default) @ mindcode-mindcode ---
[INFO] argLine set to -javaagent:C:\\Users\\k88936\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.9\\org.jacoco.agent-0.8.9-runtime.jar=destfile=E:\\WORKSPACE\\mindcode\\mindcode\\target\\jacoco.exec
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mindcode-mindcode ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ mindcode-mindcode ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ mindcode-mindcode ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 10 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ mindcode-mindcode ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 50 source files to E:\WORKSPACE\mindcode\mindcode\target\test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Դ▒▒▒а▒ 17 ▒▒ --enable-preview һ▒▒ʹ▒▒ʱ▒▒Ч
  ▒▒▒▒▒▒▒а▒ 18 ֧▒▒Ԥ▒▒▒▒▒Թ▒▒ܣ▒
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Mindcode 1.0.0-SNAPSHOT ............................ SUCCESS [  1.850 s]
[INFO] mindcode-mindcode 1.1.0-SNAPSHOT ................... FAILURE [  1.569 s]
[INFO] mindcode-schemacode 1.0.0-SNAPSHOT ................. SKIPPED
[INFO] mindcode-webapp 2.0.0-SNAPSHOT ..................... SKIPPED
[INFO] mindcode-compiler 1.0.0-SNAPSHOT ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.826 s
[INFO] Finished at: 2023-06-05T23:28:01+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project mindcode-mindcode: Compilation failure
[ERROR] Դ▒▒▒а▒ 17 ▒▒ --enable-preview һ▒▒ʹ▒▒ʱ▒▒Ч
[ERROR]   ▒▒▒▒▒▒▒а▒ 18 ֧▒▒Ԥ▒▒▒▒▒Թ▒▒ܣ▒
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :mindcode-mindcode
*****
*****
*****   To run Mindcode locally, you need to have a PostgreSQL database accessible.
*****   You have a few choices:
*****
*****       - Install PostgreSQL for Windows: https://www.postgresql.org/download/windows/
*****
*****       - Use Docker to run PostgreSQL:
*****
*****             Download Docker from https://www.docker.com/get-started
*****             Once done, start a PostgreSQL instance:
*****                 docker run -p 5432:5432 --name mindcode -v mindcode -e POSTGRES_HOST_AUTH_METHOD=trust postgres:latest
*****
*****   If your PostgreSQL instance is not available at postgres://127.0.0.1:5432/mindcode_development, edit
*****   both Spring configuration files and set the correct values:
*****
*****      webapp/src/main/resources/application.properties
*****      webapp/src/test/resources/application.properties
*****
▒▒▒▒: ▒Ҳ▒▒▒▒▒▒޷▒▒▒▒▒▒▒▒▒ info.teksol.mindcode.webapp.WebappApplication
ԭ▒▒: java.lang.ClassNotFoundException: info.teksol.mindcode.webapp.WebappApplication

andi experience test failure and compile failure even i deleted the test file  
i run bin/run-local  in git bash

**Comment by cardillan** [comment]
@k88936, aren't you trying to run docker-compose from a bash terminal on Windows? That probably won't work. You should run `docker-compose up --build` right from Windows Terminal (cmd.exe).

Likewise, don't run bin/run-local from a bash terminal, run bin/webapp.bat from Windows Terminal (after setting the environment variables including JAVA_HOME).

Let me know if you have problems getting this work.

**Comment by cardillan** [comment]
The [Native installation](https://github.com/cardillan/mindcode#native-installation) section of the Readme file has been expanded to cover Windows/Linux differences.

@k88936 thanks for pointing out the Readme didn't properly cover Windows installation.

**Pull request closed without merging**
